// ==UserScript==
// @name         Warframe Auto Redeem Codes
// @namespace    https://github.com/schalkburger/website-enhancements
// @match        https://www.warframe.com/promocode
// @version      1.1.7
// @author       DAN (and Schalk Burger)
// @description  Auto Redeem Warframe Codes
// @grant        none
// ==/UserScript==

(function () {
  "use strict";

  const SCRIPT_NAME = "Warframe Auto Redeem Codes";
  const COOLDOWN_MS = 10000;

  const RAW_CODES = `MISTLETOE2025, ZEXIONTAT, QUEENMISRULE, OLDPEACE-QQKXJ, WF-IRONMOUSE, MOVEMBER2025, QTCC10KBUNDLE, QTCC5KREWARD, PRIDE2025, 2020ZERO, AESOPYOLIAN, BLACKNATO974, CRUSADER, DEUS, EVECAPTURA, LAURIEEELG, MYLAH, RWERESS, RICKUNPRIME, SECRIOTMCFLY, SHINOBIFUFU, VECTOR, VEROZ, STALLORDD, GASTEL, NEONESS007, RELIQUARY, WALTERDV, SPECIALEFFECT, UREIFEN, RAHNY, MISTERGAMER, MECORE, MAOMIX, LUCIANPLAYSALLDAY, KENSHINWF, ITSJUSTTOE, ENDOTTI_, EDRICK, DANILY, CALAMITYDEATH, BLUEBERRYCAT, AUNTIETAN, QUADLYSTOP, JUSTHAILEY, KYAII, OTTOFYRE, RETROALCHEMIST, WARFRAMEFLO, PHONGFU, CODOMA, THEPANDA, XBOCCHANVTX, PYRRHICSERENITY, CARCHARA, LIGHTMICKE, NOMNOM, MJIKTHIZE, OZKU, DESTROHIDO, IM7HECLOWN, CANOFCRAIG, NP161, 6IXGATSU, LADYNOVITA, FERREUSDEMON, VASHKA, SILVERVALE, KIRDY, DARIKAART, DEATHMAGGOT, FATEDSCHRONICLES, NELOSART, RIKENZ, DAIDAIKIRI, WEALWEST, TORTOISE, PRIDE2024, PLEXICOSPLAY, LIGHTNINGCOSPLAY, BUFF00N, AKARI, PRIDE2023, SEARYN, SPANDY, SCALLION, MRROADBLOCK, INFERNOTHEFIRELORD, FR4G-TP, FATED2PERISH, ETERION, CROWDI, BLUYAYOGAMER, BLAZINGCOBALT, CONFUSEDWARFRAME, SPACEWAIFU, PAPATLION, MEDUSACAPTURES, FINLAENA, ARGONSIX, SILENTMASHIKO, MRWARFRAMEGUY, LILLEXI, YOURLUCKYCLOVER, VASHCOWAII, VARLINATOR, TWILA, THEKENGINEER, STR8OPTICROYAL, SIEJOUMBRA, SCARLETMOON, PURPLEFLURP, PURKINJE, PRIMEDAVERAGE, POKKETNINJA, PANDAAHH, OOSIJ, HAPPINESSDARK, EMPYREANCAP, DATLOON, CONCLAVEDISCORD, COLDTIGER, COLDSCAR, CHELESTRA, CASARDIS, BLACKONI, ASURATENSHI, EMOVJ, PARVOS, ADMIRALBAHROO, AEONKNIGHT86, AGAYGUYPLAYS, ALAINLOVE, ALEXANDERDARIO, AMPROV, ANGRYUNICORN, ANJETCAT, ANNOYINGKILLAH, ASHISOGITENNO, AVELNA, AZNITROUS, BIGJIMID, BRAZILCOMMUNITYDISCORD, BRICKY, BROZIME, BURNBXX, BWANA, CALEYEMERALD, CEPHALONSQUARED, CGSKNACKIE, CHACYTAY, CHAR, CLEONATURIN, COHHCARNAGE, COPYKAVAT, CPT_KIM, DANIELTHEDEMON, DASTERCREATIONS, DAYJOBO, DEBBYSHEEN, DEEJAYKNIGHT, DEEPBLUEBEARD, DEUCETHEGAMER, DISFUSIONAL, DILLYFRAME, DIMITRIV2, DJTECHLIVE, DKDIAMANTES, DNEXUS, EDUIY16, ELDANKER, ELGRINEEREXILIADO, ELICEGAMEPLAY, ELNORAELEO, EXTRACREDITS, FACELESSBEANIE, FASHIONFRAMEISENDGAME, FEELLIKEAPLAYER, FLOOFYDWAGON, FROSTYNOVAPRIME, FROZENBALLZ, GARA, GERMANCOMMUNITYDISCORD, GINGY, GLAMSHATTERSKULL, GOLDEN, GRINDHARDSQUAD, H3DSH0T, HOMIINVOCADO, HOTSHOMSTORIES, HYDROXATE, IFLYNN, IKEDO, INFODIVERSAO, IWOPLY, JAMIEVOICEOVER, JESSITHROWER, JOEYZERO, JORIALE, JUSTRLC, K1LLERBARBIE, KAVATSSCHROEDINGER, KINGGOTHALION, KIRARAHIME, KIWAD, KR1PTONPLAYER, KRETDUY, LADYTHELADDY, LEODOODLING, LEYZARGAMINGVIEWS, L1FEWATER, LYNXARIA, MACHO, MADFURY, MAKARIMORPH, MCGAMERCZ, MCMONKEYS, MHBLACKY, MICHELPOSTMA, MIKETHEBARD, MISSFWUFFY, MOGAMU, MRSTEELWAR, NOSYMPATHYY, ODDIEOWL, ORIGINALWICKEDFUN, ORPHEUSDELUXE, PAMMYJAMMY, PLAGUEDIRECTOR, POSTITV, PYRAH, PROFESSORBROMAN, RAGINGTERROR, RAHETALIUS, RAINBOWWAFFLES, RELENTLESSZEN, REYGANSO, RIPPZ0R, RITENS, ROYALPRAT, RUSTYFIN, R/WARFRAME, SAPMATIC, SARAHTSANG, SERDARSARI, SHARLAZARD, SHENZHAO, SHERPA, SHUL, SILLFIX, SKILLUP, SMOODIE, SN0WRC, STRIPPIN, STUDIOCYEN, TACTICALPOTATO, TANCHAN, TBGKARU, TINBEARS, TEAWREX, TENNOFOREVER, THEGAMIO, TIOMARIO, TIORAMON, TOTALN3WB, TOXICKTOE, TRASHFRAME, TRIBUROS, UNREALYUKI, VAMP6X6X6X, VERNOC, VOIDFISSUREBR, VOLI, VOLTTHEHERO, VVHITEANGEL, WANDERBOTS, WARFRAMECOMMUNITYDISCORD, WARFRAMERUNWAY, WARFRAMEWIKI, WIDESCREENJOHN, WOXLI, XENOGELION, XXVAMPIXX, ZARIONIS, ZXPFER`;

  const promoCodes = RAW_CODES.split(/[\n,]/)
    .map((c) => c.trim())
    .filter((c) => c.length > 0);

  const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

  const startAutoRedeem = async () => {
    // 1. Check local storage for the current index
    let currentIndex = parseInt(localStorage.getItem("wf_redeem_index")) || 0;

    if (currentIndex >= promoCodes.length) {
      console.log(`[${SCRIPT_NAME}] All codes finished! Run 'localStorage.removeItem("wf_redeem_index")' in console to restart.`);
      return;
    }

    console.log(`[${SCRIPT_NAME}] Resuming from index ${currentIndex}/${promoCodes.length}`);

    for (let i = currentIndex; i < promoCodes.length; i++) {
      const code = promoCodes[i];

      // 2. CRITICAL: Save NEXT index BEFORE we submit
      // This ensures if the page reloads, we don't try this code again.
      localStorage.setItem("wf_redeem_index", i + 1);

      const input = document.querySelector("#promoCode-input");
      const submitBtn = document.querySelector("#promoCode-submit");

      if (input && submitBtn) {
        console.log(`[${SCRIPT_NAME}] Attempting: ${code}`);
        input.value = code;
        input.dispatchEvent(new Event("input", { bubbles: true }));
        input.dispatchEvent(new Event("change", { bubbles: true }));

        submitBtn.click();

        // Wait for potential modal/reload
        console.log(`[${SCRIPT_NAME}] Code submitted. Cooling down for ${COOLDOWN_MS / 1000}s...`);
        await delay(COOLDOWN_MS);
      } else {
        console.error("Elements missing! Page might be loading...");
        await delay(5000);
        i--; // Retry this index
      }
    }
  };

  // Run on page load
  window.addEventListener("load", () => {
    console.log(`[${SCRIPT_NAME}] Initializing...`);
    setTimeout(startAutoRedeem, 5000);
  });
})();
